[project]
name = "tpl-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "black>=25.1.0",
    "fastapi>=0.115.8",
    "isort>=6.0.0",
    "pytest>=8.3.4",
    "ruff>=0.9.4",
]
